SELECT
    CAST(STORE AS INTEGER) AS store,
    CAST(DATE AS DATE) AS date,
    CAST(TEMPERATURE AS FLOAT) AS temperature,
    CAST(FUEL_PRICE AS FLOAT) AS fuel_price,
    CAST(CPI AS FLOAT) AS cpi,
    CAST(UNEMPLOYMENT AS FLOAT) AS unemployment
FROM STAGING.RETAIL_FEATURES
WHERE STORE IS NOT NULL
  AND DATE IS NOT NULL